import type { NextPage } from 'next'
import Head from 'next/head'
import GameComponent from '../components/Game'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <h1 className={styles.title}>
          Worldle Insights
        </h1>
        <div>
          <button>Login (Todo) </button>
        </div>
      </nav>

      <main className={styles.main}>
        <GameComponent />
      </main>
    </div>
  )
}

export default Home
